version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped
    ports:
      - "4810:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
    - "host.docker.internal:host-gateway"

  backend_rag:
    container_name: backend_rag
    build: 
      context: ./src/app
      dockerfile: Dockerfile.app
    image: backend_rag:latest
    ports:
      - 4830:7000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - "./src/app:/home/root/app"


  rag_gradio_interface:
    container_name: rag_gradio_interface
    build: 
      context: ./src/gradio_interface
      dockerfile: Dockerfile
    image: "rag_gradio_interface:latest"
    env_file:
      - ./.env
    ports:
      - 4840:7000
    volumes:
      - "./src/gradio_interface:/home/root/gradio_interface"
    extra_hosts:
      - "host.docker.internal:host-gateway"
